FROM golang:1.14

RUN mkdir -p /go/src/github.com/pengliheng/golang-api/backend

COPY . /go/src/github.com/pengliheng/golang-api/backend

WORKDIR /go/src/github.com/pengliheng/golang-api/backend

# RUN curl -fLo ~/.air https://raw.githubusercontent.com/cosmtrek/air/master/bin/linux/air
RUN go get -u github.com/cosmtrek/air

RUN go get

# RUN chmod +x ~/.air

# RUN cp ~/.air /usr/bin/air

# CMD [ "go run main.go" ]
